[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5.37", features = ["derive"] }
legalos-api = { path = "../crates/api" }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
totp-rs = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
