# CONDSTORE sans QRESYNC (chemin proche de Gmail). Les MODSEQ restent actifs.
base_dir = /tmp/dovecot
listen = *
protocols = imap
disable_plaintext_auth = no
auth_mechanisms = plain login
mail_location = maildir:/tmp/mail/%u
first_valid_uid = 100
first_valid_gid = 100
mailbox_list_index = yes

passdb {
  driver = static
  args = password=MotDePasseCapa123!
}

userdb {
  driver = static
  args = uid=dovecot gid=dovecot home=/tmp/mail/%u
}

namespace inbox {
  inbox = yes
}

protocol imap {
  imap_capability = IMAP4rev1 LITERAL+ SASL-IR ID ENABLE IDLE SORT THREAD=REFERENCES MULTIAPPEND UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED ESEARCH WITHIN BINARY MOVE CONDSTORE
}
